MISSING VALUES
1.Missing Completely at random-No reason for missing value
2.Missing at Random- Missing values are systematically related to the observed data
3.Missing data not at random-dependant on multiple factores

In [2]:
import seaborn as sns

In [3]:
df=sns.load_dataset('titanic')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
#simple way is just delete missing value row -but it will loose alot of data
df.dropna().shape

(182, 15)

In [9]:
#Column wise would be better 
df.dropna(axis=1).head()

,survived,pclass,sex,sibsp,parch,fare,class,who,adult_male,alive,alone
0,0,3,male,1,0,7.2500,Third,man,True,no,False
1,1,1,female,1,0,71.2833,First,woman,False,yes,False
2,1,3,female,0,0,7.9250,Third,woman,False,yes,True
3,1,1,female,1,0,53.1000,First,woman,False,yes,False
4,0,3,male,0,0,8.0500,Third,man,True,no,True

Imputation Missing values

In [ ]:
##Using mean to fill missing value 
df['age_mean']=df['age'].fillna(df['age'].mean())

Mean imputation works well when we have normally distributed data

In [11]:
df[['age_mean','age']]

      age_mean   age
0    22.000000  22.0
1    38.000000  38.0
2    26.000000  26.0
3    35.000000  35.0
4    35.000000  35.0
..         ...   ...
886  27.000000  27.0
887  19.000000  19.0
888  29.699118   NaN
889  26.000000  26.0
890  32.000000  32.0

[891 rows x 2 columns]

2.Median value imputation - when we have outliers like not normal distrubution

In [12]:
df['age_median']=df['age'].fillna(df['age'].median())

In [14]:
df[['age_mean','age_median','age']]

      age_mean  age_median   age
0    22.000000        22.0  22.0
1    38.000000        38.0  38.0
2    26.000000        26.0  26.0
3    35.000000        35.0  35.0
4    35.000000        35.0  35.0
..         ...         ...   ...
886  27.000000        27.0  27.0
887  19.000000        19.0  19.0
888  29.699118        28.0   NaN
889  26.000000        26.0  26.0
890  32.000000        32.0  32.0

[891 rows x 3 columns]

3.Median imputation-when we have catagorical varible

In [23]:
mode_value=df[df['embarked'].notna()]['embarked'].mode()[0]

In [24]:
mode_value

'S'

In [25]:
df['embarked_mode']=df['embarked'].fillna(mode_value)

In [27]:
df[['embarked','embarked_mode']]

    embarked embarked_mode
0          S             S
1          C             C
2          S             S
3          S             S
4          S             S
..       ...           ...
886        S             S
887        S             S
888        S             S
889        C             C
890        Q             Q

[891 rows x 2 columns]

Handling Imbalanced Dataset-

1.Up Sampling
2.Down sampling
Two techniques

In [3]:
#data encoding
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Users/piyushajitchavan/Desktop/TransferMain/PYTHON/venv/lib/python3.11/site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 3.6 MB/s  0:00:02 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.0-cp311-cp311-macosx_14_0_arm64.whl (20.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 5.1 MB/s  0:00:04m0:00:0100:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.0 threadpoolctl-3.6.0